---
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: controlplane
spec:
  ironic:
    enabled: false
    template:
      ironicConductors: []
  manila:
    enabled: false
    template:
      manilaShares: {}
  horizon:
    enabled: false
  heat:
    enabled: false
  cinder:
    enabled: false
  dns:
    enabled: false
  octavia:
    enabled: false
  swift:
    enabled: false
  barbican:
    enabled: false