---
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: controlplane
spec:
  glance:
    template:
      glanceAPIs:
        default:
          type: single
          replicas: 1
