---
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: controlplane
spec:
  galera:
    enabled: true
    templates:
      openstack:
        replicas: 1
      openstack-cell1:
        replicas: 1
  rabbitmq:
    templates:
      rabbitmq:
        replicas: 1
        requests:
          cpu: 1
          memory: 512M
        limits:
          cpu: 1
          memory: 512M
      rabbitmq-cell1:
        replicas: 1
        requests:
          cpu: 1
          memory: 512M
        limits:
          cpu: 1
          memory: 512M
  memcached:
    enabled: true
    templates:
      memcached:
        replicas: 1
  ovn:
    template:
      ovnController:
        replicas: 1
        external-ids:
          ovn-encap-type: geneve
      ovnDBCluster:
        ovndbcluster-nb:
          replicas: 1
          dbType: NB
          storageRequest: 10G
        ovndbcluster-sb:
          replicas: 1
          dbType: SB
          storageRequest: 10G
      ovnNorthd:
        replicas: 1
  ovs:
    template:
      external-ids:
        system-id: "random"
        ovn-bridge: "br-int"
        ovn-encap-type: "geneve"
